### ISSUE TITLE
NHL.tv login / password issue

### ISSUE THREAD

**Issue by D156u153** [eracknaphobia/repo.eracknaphobia#4]
I had an issue where your addon would not properly send my NHL.tv password in the 2016.10.13 plugin version. I didnt look at the code but I am assuming it is because the password contained a special character "\" and the shell was probably escaping the "\" out. Figuring that was the culprit a simply change to my password not using a special character resolved the problem but you may consider sanity checking things in case others use those characters and may not be familiar with how the shell may interpret them.

Thanks for the great work!

**Comment by eracknaphobia** [comment]
Good catch, I'll add a fix in the next release.
